### ISSUE TITLE
sp-login-form template-url not working?

### ISSUE THREAD

**Issue by surfjedi** [stormpath/stormpath-sdk-angularjs#131]
I have implemented a custom template via the directions in http://docs.stormpath.com/angularjs/sdk/#/api/stormpath.spLoginForm:spLoginForm

But it won't over ride the default template?

Any ideas?

**Comment by drpalaric** [comment]
What's your code look like?

**Comment by surfjedi** [comment]
Sorted it by just duplicating .tpls  and modifying that
