### ISSUE TITLE
Has this been tested with ui-router 0.3?

### ISSUE THREAD

**Issue by surfjedi** [stormpath/stormpath-sdk-angularjs#148]
I just tried to update my app that has been running great on this SDK verion 1.0.0 and UI router 0.2.18. 
But updating to ui-router 0.3 gets me this error:
Failed to instantiate module app.auth due to:
TypeError: Cannot create property 'resolveAs' on string 'login'

Changing Ui-router back to 0.2.18 fixes it.

Any Ideas?

**Comment by robertjd** [comment]
I'm looking at the UI Router changelog, and I don't see a 0.3 version?  It seems that 0.2.18 is the last version before 1.0.0-alpha.1

**Comment by surfjedi** [comment]
https://github.com/angular-ui/ui-router/blob/0.3.0/CHANGELOG.md

I agree its hard to find but there - and 0.3 is still for angular 1.x but once they bump to ui-router 1.xx that for anuglar 2.x.x

**Comment by robertjd** [comment]
Thanks.  0.3 looks like a strange release, we definitely have not tested against it.  I would stick with 0.2.18.
