### ISSUE TITLE
Group authorization

### ISSUE THREAD

**Issue by gomoto** [stormpath/stormpath-sdk-angularjs#149]
stormpath-sdk-angularjs v1.0.0
express-stormpath v3.1.2

After adding group authorization to ui-router state configuration,

```
.state('tasks', {
  url: '/tasks',
  template: '<tasks></tasks>',
  sp: {
    authorize: {
      group: 'admins'
    }
  }
})
```

when a user, whether or not he is part of the 'admins' group, goes to /tasks, he will get `TypeError: Cannot read property 'items' of undefined` which points to `this.groups.items` in stormpath-sdk-angularjs.min.js:

```
b.module("stormpath.userService", ["stormpath.CONFIG"]).provider("$user", [function() {
        function a(a) {
            var b = this;
            Object.keys(a).map(function(c) {
                b[c] = a[c]
            })
        }
        a.prototype.inGroup = function(a) {
            return this.groups.items.filter(function(b) {
                return b.name === a
            }).length > 0
        }

        // ...

    }
]);
```

In express-stormpath, groups are expanded:

```
app.use(stormpath.init(app, {
  expand: {
    groups: true
  },
  website: true,
  web: {spaRoot: indexRoute}
}));
```

Is there an error in my setup, or is this an error in stormpath-sdk-angularjs?

**Comment by robertjd** [comment]
Thanks for getting in touch.  You'll need to explicitly add expansion to the `/me` route, so your configuration would look like this:

```
app.use(stormpath.init(app, {
  web: {
    me: {
      expand: {
        customData: true
      }
    }
  }
});
```

More information on the current user endpoint is available here: http://docs.stormpath.com/nodejs/express/latest/user_data.html#current-user-json-api

I hope this helps!

**Comment by gomoto** [comment]
Works perfectly. Thank you!

**Comment by robertjd** [comment]
No prob, happy to help!
