### ISSUE TITLE
Issue running stormpath-sdk-angularjs.js (non minified) from bower

### ISSUE THREAD

**Issue by edjiang** [stormpath/stormpath-sdk-angularjs#154]
![image](https://cloud.githubusercontent.com/assets/918770/16496668/e55d8762-3ea7-11e6-9319-54f94ac679d8.png)

For some reason, the stormpath-sdk-angularjs.js has a unicode 0xa0 character in it right there on line 1405. It's not in the github repo, but it's in the version downloaded from bower.

**Comment by mraible** [comment]
Cannot reproduce with the latest version:

```
bower install stormpath-sdk-angularjs --save
bower stormpath-sdk-angularjs#* cached https://github.com/stormpath/stormpath-sdk-angularjs.git#1.1.0
bower stormpath-sdk-angularjs#*         validate 1.1.0 against https://github.com/stormpath/stormpath-sdk-angularjs.git#*
```

Tested against https://github.com/stormpath/angularjs-spring-boot-stormpath-example
