### ISSUE TITLE
Make an option to use auth-header instead of cookies

### ISSUE THREAD

**Issue by arealmaas** [stormpath/stormpath-sdk-angularjs#16]
I have the API on a different URL than the angular application. Cookies don't work very well with different host names between the FE and the API. Would be nice if i had the option of sending the token in an auth-header instead of a cookie.

**Comment by lhazlewood** [comment]
Can you please help me understand the implementation difference?

With CORS, the server has to tell the browser which headers the browser is allowed to transmit during a cross-origin request by listing them in the `Access-Control-Request-Headers` response header.  

This means either `Cookie` or `YOUR-CUSTOM-HEADER` has to be listed in that list to allow the other domain to send the bearer token.  If you added `Cookie`, it would just work, no need for a custom header.

Thoughts?

**Comment by robertjd** [comment]
Hi @AlmaasAre 

The cookie should still work even if the API is on a different URL, but you will have to instruct the XHR object to use the `withCredentials` flag (Angular's $http object accepts this).

This has prompted me to write an example app that shows how to do this with our SDKs.  Are you using our Express SDK with Angular?

**Comment by lhazlewood** [comment]
Ah, even better - no need to even mess with that particular CORS header.

**Comment by robertjd** [comment]
D'oh!  I'm silly (and lacking caffeine).  The same cookie _wont_ work in this situation, because it's stored on the other domain (it's issued from the other domain).

So yes, cross domain requires you to start passing the access token in a HTTP header.  As you saw in #5 this is something that I need to support with this library.  I'm cranking away on that now..

**Comment by arealmaas** [comment]
yes exactly. Thanks, that's awesome :)

I'm using the express sdk and angular sdk.

I think an http-header would be cleanest to  have for cors Idd. The alternative would be to accept cross site scripting.

**Comment by robertjd** [comment]
Hi @AlmaasAre 

Now that the holiday weekend is over... :)  My original comment about using the `withCredentials` option is in fact the correct solution to this problem.

I've published an update to this library, it now uses that option.  I've also pushed an update to [stormpath-sdk-express](https://github.com/stormpath/stormpath-sdk-express) (It had some bugs with the CORS implementation).

Please update these modules and give it a go, things should be working across different ports now!

Cheers,
Robert

**Comment by arealmaas** [comment]
Alright, thank you!
