### ISSUE TITLE
Sample App Odd Experience

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-angularjs#161]
I'm following the Express + Angular quickstart in the Stormpath console, and am having an odd getting started experience.

Here's what I see when I open the sample application:

![screenshot 2016-08-05 10 24 47](https://cloud.githubusercontent.com/assets/90247/17444811/df82eb3c-5af6-11e6-8269-69676da5999e.png)

It looks like there should be a list of features, and there are none, which is really odd.

Also: what is yeoman and why am I seeing it all over? This is a Stormpath sample app, and that's really confusing to me.

The footer of the sample project links to some random dude's twitter, and some other github repo that has nothing to do with this app.

**Comment by robertjd** [comment]
Thanks, this is/was a Yeoman boilerplate app, this is how we introduced the module when it was first created.  At this point I no longer fill that it's necessary to maintain a Yeoman example, please see my bigger plans in #166
