### ISSUE TITLE
Sample App Login Page Issue

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-angularjs#162]
The sample app registration form lets you specify an email, password, first name, last name, and favorite color when you register.

The login page, however, says username or EMAIL and password. This should just say email since no username is shown / editable / etc. This is confusing to new users.

**Comment by robertjd** [comment]
Same comment as I left in the react sample app:  I'm okay with the default login form showing "Username or Email", as it highlights that both are possible.  If the final application supports only one or the other, that's up to the developer, and they can change that label.
