### ISSUE TITLE
Sample App Dashboard Page is Confusing

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-angularjs#163]
When I log into the sample app dashboard page, it looks like this:

![screenshot 2016-08-05 10 32 39](https://cloud.githubusercontent.com/assets/90247/17445056/f368866a-5af7-11e6-8b82-3553a888e1d7.png)

This is confusing because it lists features that all point to nowhere, but have odd descriptive names for stuff unrelated to Stormpath. This is really confusing.

**Comment by robertjd** [comment]
I agree, this is a boilerplate Yeoman app that shows a lot of non-Stormpath stuff.  I want to remove it, as enumerated in #166.
