### ISSUE TITLE
Add Sphinx Docs

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-angularjs#165]
We should have some official Sphinx documentation for this project so it blends with our other projects.

**Comment by robertjd** [comment]
We do have a guide if you're using Yeoman:

http://docs.stormpath.com/angularjs/guide/

Is there some other guide you were hoping to find?

**Comment by robertjd** [comment]
I've put together the bigger plan in #166, please review and let's continue to discuss there.

In short: I only want one documentation site for this library, not two.
