### ISSUE TITLE
Allow developers to override the STORMPATH_CONFIG

### ISSUE THREAD

**Issue by arealmaas** [stormpath/stormpath-sdk-angularjs#17]
I created a pull-request for this as a temporary fix: #15 

The use-case i had was that the API is on a different URL, so i needed a way to change the base-url for all endpoints.

**Comment by arealmaas** [comment]
An associated'ish issue: #5

**Comment by robertjd** [comment]
This has been documented, and can be found here:

https://docs.stormpath.com/angularjs/sdk/#/api/stormpath.STORMPATH_CONFIG:STORMPATH_CONFIG
