### ISSUE TITLE
When will angular 2 be available

### ISSUE THREAD

**Issue by trainerbill** [stormpath/stormpath-sdk-angularjs#170]
RC 5 is out and routing is stable.  Can it be based on material design (material2)? 

Edit:  Can we get a shell module/repo started for those of us bored enough to work on it now?

**Comment by robertjd** [comment]
Hi @trainerbill , I did start working on a prototype of a module, which you can see here:

https://github.com/robertjd/sp-ng2/

It doesn't have any documentation, but it has an example which includes the AuthPort component, which is meant to be a more general login/signup/password management component.  As it is not in NPM yet, you'll have to link to the module.  I had some problems with npm link and typescript typings, so you may find that simply copying the source into your project is less frustrating.

I'm more than happy to hear any feedback you have on this :)  It does use RxJS observables for the `user$` observable, which is meant to convey a null, false, or User object (to indicate unknown user state, logged out state, and known user state, respectively).

**Comment by mraible** [comment]
I hope to start working on an Angular 2 SDK in a couple weeks, using @robertjd's prototype as an example.

**Comment by trainerbill** [comment]
@mraible @robertjd I would be willing to contribute as well.  I think we should keep it in the stormpath repo.  Maybe we can get a branch or something to contribute to.  maybe some design discussions?  I would personally like to see it based on material2

**Comment by mraible** [comment]
@trainerbill It'd be great if we can make it CSS framework agnostic, or provide Material Design and Bootstrap versions for users. I created https://github.com/stormpath/stormpath-sdk-angularjs/issues/177 this morning because I think it'd be cool if you didn't even have to create the pages in your application. Of course, for those that want fine-grained control, they could still use directives/components in their pages.

**Comment by goncalogomes** [comment]
Just wondering if work on this is in the pipeline?
I can't get the example on the prototype working (I guess it was using older versions of angular2) so wondering if there will be an official version soon...
Thanks!

**Comment by mraible** [comment]
@goncalogomes I hope to start working on the Angular 2 SDK next week. Stay tuned!

**Comment by subatomicglue** [comment]
Exciting stuff, just starting on angular2 & stormpath now for our app...

**Comment by mraible** [comment]
Hi folks! We have some good news: our Angular2 SDK is now available in beta and we are looking for devs to take it for a spin to collect some feedback. 

https://github.com/stormpath/stormpath-sdk-angular

Let me know any questions or comments in GitHub issues for the repo above.
