### ISSUE TITLE
Controllers to Services? $scope to this?

### ISSUE THREAD

**Issue by drpalaric** [stormpath/stormpath-sdk-angularjs#18]
Hey @robertjd , 

I am looking at the SDK and wonder if `$scope` is really necessary anymore. Why not write `this.whatever = function(somethingCool){};` inside a controller, or better yet in a factory and calling it in the controller? Would you consider that? I was thinking about this after refactoring some of my code and thought it would be something worth mentioning for the Stormpath SDK. If it is a completely outrageous idea, my apologies.

**Comment by robertjd** [comment]
Hey @AbdullahAlger !

I do like this pattern, I've been using it for some of the controllers in our Admin Console application.  Thanks for dropping the note here, I'll be refactoring this library for cleanliness at some point (once it has tests!) and I'll include this change.

-Robert
