### ISSUE TITLE
Request for npm support

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-sdk-angularjs#182]
I'm not sure if this used to exist, but we have customers requesting npm support for this lib 👍

**Comment by robertjd** [comment]
This could mean a few different things, can you please clarify?  As it is right now, you should be able to download this package with npm, but how you then take that source and use it in your application is another story that probably isn't supported.

**Comment by mraible** [comment]
I've installed it via Bower and WebJars. Haven't tried npm.

**Comment by mdeggies** [comment]
Whoops, sorry guys. I was typing in the wrong name. It is stormpath-sdk-angularjs. Will update this in the README.
