### ISSUE TITLE
Support for multi-group access control?

### ISSUE THREAD

**Issue by rondanal** [stormpath/stormpath-sdk-angularjs#194]
To control access levels, I've been using groups to conditionally showing certain elements using `if-user-in-group`. I've been able to target multiple groups (hopefully, correctly) using:
```Javascript
if-user-in-group="'/moderator|admin/'"
```
I would also like to limit certain routes based on a user's group, however I can't seem to get this working with the `authorize` object:

```Javascript
angular.module('mainApp')
  .config(function ($stateProvider) {
    $stateProvider
      .state('admin', {
        url: '/admin',
        template: '<admin></admin>',
        sp: {
            waitForUser: true,
            authorize: {
                group: 'admin'
            }
        }
      });
  });
```

I would like multiple groups to access certain routes like the one above. I've tried passing an array to `group` and also creating using `"'/moderator|admin/'"` but neither of these work. 
Is this supported? How would I go about implementing this?

**Comment by mraible** [comment]
@rondanal You're in luck! We just added support for multiple groups to limit state access in the 1.1.1 release of our AngularJS SDK. However, rather than using `sp.authorize.group`, you'll want to use `data.authorities`. For example:

``` js
// Require a user to be in the admins group in order to see this state
$stateProvider
  .state('secrets', {
    url: '/admin',
    controller: 'AdminCtrl',
    data: {
      authorities: ['admins','users']
    }
  });
```

https://docs.stormpath.com/angularjs/sdk/#/api/stormpath.SpStateConfig:SpStateConfig

**Comment by rondanal** [comment]
@mraible Perfect, cheers for this!
