### ISSUE TITLE
Detecting groups through a service

### ISSUE THREAD

**Issue by Doug-Shannon** [stormpath/stormpath-sdk-angularjs#196]
Is it possible to make a $user or $auth call to get the groups a user is apart of in the controller?

**Comment by robertjd** [comment]
Hi @Doug-Shannon , the group context will be available if you have enabled the option to expand the groups of the account, this is an option on your server (it modifies the format of the `/me` response).  Here is what that looks like in our express library:

https://docs.stormpath.com/nodejs/express/latest/user_data.html#current-user-json-api

Once that is enabled, the group context will always be available via `$rootScope.user.groups` or from the `user` object that you get back from `$user.get()`.  The documentation for this is here:

https://docs.stormpath.com/angularjs/sdk/#/api/stormpath.userService.$user

I hope this helps!
