### ISSUE TITLE
Please provide status on Angular 2 integration

### ISSUE THREAD

**Issue by kristianmandrup** [stormpath/stormpath-sdk-angularjs#209]

**Comment by mraible** [comment]
Please see https://github.com/stormpath/stormpath-sdk-angular. Also, I wrote a blog post about it last November. https://stormpath.com/blog/angular-2-user-authentication

**Comment by kristianmandrup** [comment]
Thanks. Would be nice to mention this in the Readme IMO

**Comment by mraible** [comment]
Good idea! I created an issue to track this. https://github.com/stormpath/stormpath-sdk-angularjs/issues/210
