### ISSUE TITLE
Social login

### ISSUE THREAD

**Issue by Jagdeep1** [stormpath/stormpath-sdk-angularjs#25]
Hey team,

When can we expect implementation for social login?

Jagdeep

**Comment by robertjd** [comment]
Hi @Jagdeep1 

We don't provide timelines for features, but this one is high on the list.  We'll update this issue when it's released (you can also watch for pull requests), so I'll leave this open until then.

Thanks!

**Comment by Jagdeep1** [comment]
Thanks for the update. Good to know that this feature is on high priority :)

Regards
Jagdeep

**Comment by robertjd** [comment]
We will be working on this soon, closing this issue in favor of #44
