### ISSUE TITLE
Angular Directives require JQuery

### ISSUE THREAD

**Issue by voor** [stormpath/stormpath-sdk-angularjs#27]
This isn't a big deal, but you should probably denote that somewhere.  Since you are using:

``` javascript
.directive('ifUser',['$user','$rootScope',function($user,$rootScope){
  return {
    link: function(scope,element){
      $rootScope.$watch('user',function(user){
        if(user && user.href){
          element.show();
        }else{
          element.hide();
        }
      });
    }
  };
}])
```

Specifically the `element.show()` is a JQuery function.  If you don't have JQuery present you'll have a bad time.

**Comment by robertjd** [comment]
Does this actually require you to have a jQuery library on the page?  I thought Angular had some kind of internal "jQuery light" which provides the `element` API?

**Comment by voor** [comment]
Good question, I was essentially having problems without jQuery, and then everything worked when I added it in.  I'll get some logs tomorrow and post them.

**Comment by drpalaric** [comment]
Angular comes with its own version of jQuery. There should be no problems using `.show()` or `.hide()` in the directive. I haven't had problems with Stormpath, or had to add jQuery. Here is what the [ Angular docs](https://docs.angularjs.org/misc/faq) say about jQuery: 

> Does Angular use the jQuery library?
> Yes, Angular can use jQuery if it's present in your app when the application is being bootstrapped. If  jQuery is not present in your script path, Angular falls back to its own implementation of the subset of jQuery that we call jQLite.
> 
> Angular 1.3 only supports jQuery 2.1 or above. jQuery 1.7 and newer might work correctly with Angular but we don't guarantee that.

**Comment by bkyarger** [comment]
I think it does require jQuery for show() and hide().  On the docs for [jqLite/angular.element](https://docs.angularjs.org/api/ng/function/angular.element) it lists the supported methods and show/hide are not listed.

**Comment by drpalaric** [comment]
Yeah, I think you're right. However, I think that instead of resorting to jQuery, we probably should be using the ngHide and ngShow directives.

**Comment by bkyarger** [comment]
Yes, I agree.  We would like to use this without having to include jQuery at all.

**Comment by timothyej** [comment]
Thanks @bkyarger! This SDK no longer depends on jQuery, so I'm closing this issue.
