### ISSUE TITLE
Add Customization for /logout

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-angularjs#28]
It would be nice if we could customize the logout URIs.

**Comment by timothyej** [comment]
What do you mean? :) It's possible to set a custom `/logout` endpoint using `DESTROY_SESSION_ENDPOINT` of `stormpath.STORMPATH_CONFIG`.

**Comment by gemmell** [comment]
It wasn't 4 months ago.... ;)

**Comment by timothyej** [comment]
Oh, okay, I will close this then ;) Thanks! 👍
