### ISSUE TITLE
STORMPATH_CONFIG.FORM_CONTENT_TYPE='application/json' is ignored

### ISSUE THREAD

**Issue by gemmell** [stormpath/stormpath-sdk-angularjs#29]
STORMPATH_CONFIG.FORM_CONTENT_TYPE='application/json'

is ignored - our server is still getting form urlencoded, this was not broken a couple of revisions ago, so it's been introduced recently.

**Comment by robertjd** [comment]
Hi @gemmell , can you tell me which form is causing this?  I am trying the login form with the current version and I don't see this problem.  Thanks!

**Comment by gemmell** [comment]
I am not using the login form, we are using our own and:

```
controller: function ($scope, $auth, $state, $window, $user) {
...
$scope.sendLoginDetails = function login(formData) {
           ...
           $auth.authenticate(formData)
              .then(function () {
                ...
```

**Comment by robertjd** [comment]
Which version of this library?

**Comment by gemmell** [comment]
"dependencies": {
    "stormpath-sdk-angularjs": "~0.5.1",

**Comment by gemmell** [comment]
I have 

```
var app = angular.module("tkbt-site", ['yaru22.hovercard', 'ngCookies', 'stormpath', 'ngInputModified', 'ngResource', 'ngSanitize', "ui.router", "ngMessages", "ui.validate", "ngAnimate"]).config(function (STORMPATH_CONFIG) {
STORMPATH_CONFIG.AUTHENTICATION_ENDPOINT = '/api/users/login';
STORMPATH_CONFIG.CURRENT_USER_URI = '/api/users/current';
STORMPATH_CONFIG.FORM_CONTENT_TYPE = 'application/json';
});
```

**Comment by robertjd** [comment]
Your config function is overriding the default value for the form content type, and specifying json:

> STORMPATH_CONFIG.FORM_CONTENT_TYPE = 'application/json';

**Comment by gemmell** [comment]
And it is ignored and is sending urlencoded as the data. 

```
FormEncoderService.prototype.formPost = function formPost(httpRequest){
    var h = httpRequest.headers ? httpRequest.headers : (httpRequest.headers = {});
    h['Content-Type'] = STORMPATH_CONFIG.FORM_CONTENT_TYPE;
    httpRequest.data = this.encodeUrlForm(httpRequest.data);
    return httpRequest;
  };
```

I don't know the code, but the only time `FORM_CONTENT_TYPE` is used is right before it calls `encodeUrlForm` - shouldn't there be an if which doesn't `encodeUrlForm` if I have set it to application/json?

**Comment by gemmell** [comment]
Yeh, changing it to 

```
if (STORMPATH_CONFIG.FORM_CONTENT_TYPE !== 'application/json') {
    httpRequest.data = this.encodeUrlForm(httpRequest.data);
 } 
```

Means it is actually encoded as JSON when it is sent (i.e. it fixes the problem).

**Comment by robertjd** [comment]
Oh you're totally right, that got removed!  I just merged it back in :)  will publish to bower in a moment as 0.5.2 - sorry for the confusion here!
