### ISSUE TITLE
stormpath-sdk-angular.js not found

### ISSUE THREAD

**Issue by n8twj** [stormpath/stormpath-sdk-angularjs#3]
After building per README, stormpath-sdk-angular.js is 404 Not found.

stormpath-sdk-express is installed by npm within node_modules.

**Comment by robertjd** [comment]
Oops!  I'm on mobile.  It should probably be stormpath-sdk-angularjs.js

Where in the code is the issue?

**Comment by rdegges** [comment]
The issue here is documentation related: the required file isn't in the right spot. I'll fix the readme and push an update.

**Comment by n8twj** [comment]
Also, i had to npm install --save stormpath

**Comment by rdegges** [comment]
Bam, please retry this from scratch. Should be working now =)
