### ISSUE TITLE
npm install doesn't install devDependencies

### ISSUE THREAD

**Issue by syonip** [stormpath/stormpath-sdk-angularjs#4]
the readme should state "npm install --dev", or the packages.json should include the packages in "dependencies".

Also, "npm install --dev" didn't install the dependencies correctly, I had to install them one by one.

**Comment by robertjd** [comment]
Hey @syonip can you tell me which version of npm you are using?  Thanks

**Comment by robertjd** [comment]
Do you have an environment declared via NODE_ENV?  Apparently if it's set to 'production' it will skip the dev dependencies:

http://stackoverflow.com/a/27179090/998998

**Comment by syonip** [comment]
Hey Robert,
my npm version: 1.4.28.
don't have NODE_ENV set.

**Comment by robertjd** [comment]
Closing old issue
