### ISSUE TITLE
Implement localStorage strategy if detected that domain is different

### ISSUE THREAD

**Issue by robertjd** [stormpath/stormpath-sdk-angularjs#46]
Not all clients have a cookie store, for example the Iconic framework.  At the moment this library assumes that authentication is being handled by cookies.

This library should support the ability to pass the access token in the Authorization header, but the details about where the token is stored should be abstracted behind a generic interface.  If using mobile, the filesystem api should be used (or some other secure storage api where the data is scoped to the application) for storing the access token and refresh token.  For example, I Ionic promotes the use of the [SecureStorage plugin for Apache Cordova](https://github.com/Crypho/cordova-plugin-secure-storage)

We would also need to implement some client-side code that can exchange a refresh token for a new access token, if the access token expires.

Essentially, we need a client-side Oauth2 implementation that depends on a generic interface for reading and writing tokens in a secure fashion.

If it's detected that a login request is going to be posted to a different domain (via ENDPOINT_PREFIX configuration), we should instead use the `/oauth/token` endpoint, instead of the `/login` endpoint, and manage the storage of the tokens as described above.

**Comment by omgitstom** [comment]
This is really important for Client API

**Comment by robertjd** [comment]
Hi @Tweety-FER ,

One more requirement just came through.  Right now this library will send an `X-Stormpath-Agent` header on all requests, if the request is on the same domain.  This header let's us know which SDK is being used on the front-end.  We only send this header on the same domain because we don't want to cause CORS security exceptions if the remote domain has not been configured to accept this header.

But for the Client API, we do want to add this header.  So I think the rule looks like this:  if the developer has provided an ENDPOINT_PREFIX, then we should add the header to any request that is triggered by this library (such as a POST to the /oauth/token endpoint).  

Also, there's another rule: if the request is to a remote domain, and the request is not triggered by this library, then we should not send the header.  This is because the developer is likely using their own API and they won't have CORS setup to accept this header.

**Comment by the-overengineer** [comment]
@robertjd Added a simple wrapper around `$http` that can be used internally to achieve this behaviour. It wraps it with the header-adding logic, and exposes the same shorthand methods as `$http`. Moved all uses of `$http` within the application to this new `$spHttp` factory. There is, however, a slight issue in the form of:

```
Request header field X-Stormpath-Agent is not allowed by Access-Control-Allow-Headers in preflight response.
```

I'll need to run through the changes manually once that is added to the allowed headers.

**Comment by robertjd** [comment]
Thanks @Tweety-FER ! Yes, we have to add the necessary CORS response from the server, that should be coming to the dev box soon
