### ISSUE TITLE
Login post needs to be Oauth compliant

### ISSUE THREAD

**Issue by robertjd** [stormpath/stormpath-sdk-angularjs#6]
Right now it's posting a JSON object, but it should be posting a for `application/x-www-form-urlencoded` - this is required to be compatible with our Java SDK

**Comment by drpalaric** [comment]
Is this still an issue? I was looking at the docs and it mentioned that it is only configured for `application/json`. Do you want it to post `application/x-www-form-urlencoded`?

**Comment by robertjd** [comment]
Thanks for reminding me!  Yes, this issue is resolved now.  The module now uses, by default, `application/x-www-form-urlencoded` (per the Oauth spec).  You have to opt-in to JSON by setting:

`STORMPATH_CONFIG.FORM_CONTENT_TYPE='application/json'`
