### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined.

### ISSUE THREAD

**Issue by surendrakumarkhatik** [stormpath/stormpath-sdk-angularjs#76]
Hello,
I am using this module on front end and   "express-stormpath": "^2.0.14", in backend. I want to apply group filter on state.

sp: {
            authorize: {
                group: 'admins'
            }
        }
but it's give me an angular error. "TypeError: Cannot read property 'filter' of undefined.".
Please help me. 
Thanks in advance :)

**Comment by robertjd** [comment]
Please ensure that you are expanding the groups object on the server.  That can be done with this configuration:

```
app.use(stormpath.init(app, {
  expand: {
    customData: true,
    groups: true
  }
});
```

I hope this helps.  More information on the expansions can be found here:

http://docs.stormpath.com/nodejs/express/latest/user_data.html#automatic-expansion

**Comment by surendrakumarkhatik** [comment]
Thank you so much @robertjd  :+1:

**Comment by robertjd** [comment]
No problem, did it resolve your issue?  Thanks.

**Comment by surendrakumarkhatik** [comment]
@robertjd 
You previous answer working but i want to assign multiple group to a state. How i can do that
Please help me. 
Thanks in advance :)

**Comment by robertjd** [comment]
Happy to help! Do you mean that you want to require the user to be in
multiple groups, as an authorization requirement for a UI state?

**Comment by surendrakumarkhatik** [comment]
Yes :)
Thanks for quick response.
Say if a state can access admin as well as user group then how i can this to ui route
