### ISSUE TITLE
sp-logout Not Working

### ISSUE THREAD

**Issue by surendrakumarkhatik** [stormpath/stormpath-sdk-angularjs#77]
Hello @robertjd 
<a ui-sref="login" sp-logout>Sign Out</a></li>, 
I am using sp-logout for logout. Let say i am on user dashboard page then i click logout. But it remain on same page but all auth navbar hide and login register option display.

Please help me.

Thanks in advance :)

**Comment by robertjd** [comment]
My apologies, our documentation was out of date.  I just pushed the latest docs, which you can read for the logout directive here (you may have to force-reload the page):

http://docs.stormpath.com/angularjs/sdk/#/api/stormpath.spLogout:spLogout

The logout directive will only delete the authentication cookies.  You need to listen for this event and then tell your application what it should do after logout.  In this example, we send the user back to the login view state:

``` javascript
 $rootScope.$on('$sessionEnd',function () {
   $state.transitionTo('login');
 });
```

Please let me know if this helps.

**Comment by surendrakumarkhatik** [comment]
Yes, it's working fine.

Thank you so much :+1:
