### ISSUE TITLE
How to change email content, or maybe translate it?

### ISSUE THREAD

**Issue by jonathansolorzn** [stormpath/stormpath-sdk-angularjs#85]
I'd like to know how to change the message of the reset passwork mail, or maybe just translate it to another idiom?

**Comment by chanoch** [comment]
Hi,

Emails are sent by stormpath on your application's behalf on a directory by directory basis.

To change the email text, you need to:
- Log in to stormpath (https://api.stormpath.com/login)
- Click on Directories
- Edit the directory you want to configure from the Actions options
- Click  the workflows menu option
- Click on the Password Reset tab
- You will find two templates, one for password reset request and one for password reset success

**Comment by jonathansolorzn** [comment]
Thank you!
