### ISSUE TITLE
Version 0.8.2 results in XHR errors

### ISSUE THREAD

**Issue by timothyej** [stormpath/stormpath-sdk-angularjs#94]
Using the latest version via bower, login results in XHR errors. But when using the files from the example app, everything works nicely.

Need to investigate this further as I haven't verified this behaviour myself yet.

**Comment by gchatter** [comment]
Note: happens in chrome.

**Comment by robertjd** [comment]
@gchatter do you still have the problem if you use the 0.9.0 version?

**Comment by drpalaric** [comment]
@robertjd I didn't get an error using 0.9.0.
